ClientTables = {}

ClientTables.WeaponNames = {
	[tostring(`WEAPON_UNARMED`)] = 'Unarmed',
	[tostring(`GADGET_PARACHUTE`)] = 'Parachute',
	[tostring(`WEAPON_KNIFE`)] = 'Knife',
	[tostring(`WEAPON_NIGHTSTICK`)] = 'Nightstick',
	[tostring(`WEAPON_HAMMER`)] = 'Hammer',
	[tostring(`WEAPON_BAT`)] = 'Baseball Bat',
	[tostring(`WEAPON_CROWBAR`)] = 'Crowbar',
	[tostring(`WEAPON_GOLFCLUB`)] = 'Golf Club',
	[tostring(`WEAPON_BOTTLE`)] = 'Bottle',
	[tostring(`WEAPON_DAGGER`)] = 'Antique Cavalry Dagger',
	[tostring(`WEAPON_HATCHET`)] = 'Hatchet',
	[tostring(`WEAPON_KNUCKLE`)] = 'Knuckle Duster',
	[tostring(`WEAPON_MACHETE`)] = 'Machete',
	[tostring(`WEAPON_FLASHLIGHT`)] = 'Flashlight',
	[tostring(`WEAPON_SWITCHBLADE`)] = 'Switchblade',
	[tostring(`WEAPON_BATTLEAXE`)] = 'Battle Axe',
	[tostring(`WEAPON_POOLCUE`)] = 'Pool Cue',
	[tostring(`WEAPON_PIPEWRENCH`)] = 'Wrench',
	[tostring(`WEAPON_STONE_HATCHET`)] = 'Stone Hatchet',

	[tostring(`WEAPON_PISTOL`)] = 'Pistol',
	[tostring(`WEAPON_PISTOL_MK2`)] = 'Pistol Mk2',
	[tostring(`WEAPON_COMBATPISTOL`)] = 'Combat Pistol',
	[tostring(`WEAPON_PISTOL50`)] = 'Pistol .50	',
	[tostring(`WEAPON_SNSPISTOL`)] = 'SNS Pistol',
	[tostring(`WEAPON_SNSPISTOL_MK2`)] = 'SNS Pistol Mk2',
	[tostring(`WEAPON_HEAVYPISTOL`)] = 'Heavy Pistol',
	[tostring(`WEAPON_VINTAGEPISTOL`)] = 'Vintage Pistol',
	[tostring(`WEAPON_MARKSMANPISTOL`)] = 'Marksman Pistol',
	[tostring(`WEAPON_REVOLVER`)] = 'Heavy Revolver',
	[tostring(`WEAPON_REVOLVER_MK2`)] = 'Heavy Revolver Mk2',
	[tostring(`WEAPON_DOUBLEACTION`)] = 'Double-Action Revolver',
	[tostring(`WEAPON_APPISTOL`)] = 'AP Pistol',
	[tostring(`WEAPON_STUNGUN`)] = 'Stun Gun',
	[tostring(`WEAPON_FLAREGUN`)] = 'Flare Gun',
	[tostring(`WEAPON_RAYPISTOL`)] = 'Up-n-Atomizer',

	[tostring(`WEAPON_MICROSMG`)] = 'Micro SMG',
	[tostring(`WEAPON_MACHINEPISTOL`)] = 'Machine Pistol',
	[tostring(`WEAPON_MINISMG`)] = 'Mini SMG',
	[tostring(`WEAPON_SMG`)] = 'SMG',
	[tostring(`WEAPON_SMG_MK2`)] = 'SMG Mk2',
	[tostring(`WEAPON_ASSAULTSMG`)] = 'Assault SMG',
	[tostring(`WEAPON_COMBATPDW`)] = 'Combat PDW',
	[tostring(`WEAPON_MG`)] = 'MG',
	[tostring(`WEAPON_COMBATMG`)] = 'Combat MG',
	[tostring(`WEAPON_COMBATMG_MK2`)] = 'Combat MG Mk2',
	[tostring(`WEAPON_GUSENBERG`)] = 'Gusenberg Sweeper',
	[tostring(`WEAPON_RAYCARBINE`)] = 'Unholy Deathbringer',

	[tostring(`WEAPON_ASSAULTRIFLE`)] = 'Assault Rifle',
	[tostring(`WEAPON_ASSAULTRIFLE_MK2`)] = 'Assault Rifle Mk2',
	[tostring(`WEAPON_CARBINERIFLE`)] = 'Carbine Rifle',
	[tostring(`WEAPON_CARBINERIFLE_MK2`)] = 'Carbine Rifle Mk2',
	[tostring(`WEAPON_ADVANCEDRIFLE`)] = 'Advanced Rifle',
	[tostring(`WEAPON_SPECIALCARBINE`)] = 'Special Carbine',
	[tostring(`WEAPON_SPECIALCARBINE_MK2`)] = 'Special Carbine Mk2',
	[tostring(`WEAPON_BULLPUPRIFLE`)] = 'Bullpup Rifle',
	[tostring(`WEAPON_BULLPUPRIFLE_MK2`)] = 'Bullpup Rifle Mk2',
	[tostring(`WEAPON_COMPACTRIFLE`)] = 'Compact Rifle',

	[tostring(`WEAPON_SNIPERRIFLE`)] = 'Sniper Rifle',
	[tostring(`WEAPON_HEAVYSNIPER`)] = 'Heavy Sniper',
	[tostring(`WEAPON_HEAVYSNIPER_MK2`)] = 'Heavy Sniper Mk2',
	[tostring(`WEAPON_MARKSMANRIFLE`)] = 'Marksman Rifle',
	[tostring(`WEAPON_MARKSMANRIFLE_MK2`)] = 'Marksman Rifle Mk2',

	[tostring(`WEAPON_GRENADE`)] = 'Grenade',
	[tostring(`WEAPON_STICKYBOMB`)] = 'Sticky Bomb',
	[tostring(`WEAPON_PROXMINE`)] = 'Proximity Mine',
    [tostring(`WEAPON_PIPEBOMB`)] = 'Pipe Bomb',
	[tostring(`WEAPON_SMOKEGRENADE`)] = 'Tear Gas',
	[tostring(`WEAPON_BZGAS`)] = 'BZ Gas',
	[tostring(`WEAPON_MOLOTOV`)] = 'Molotov',
	[tostring(`WEAPON_FIREEXTINGUISHER`)] = 'Fire Extinguisher',
	[tostring(`WEAPON_PETROLCAN`)] = 'Jerry Can',
	[tostring(`WEAPON_BALL`)] = 'Ball',
	[tostring(`WEAPON_SNOWBALL`)] = 'Snowball',
	[tostring(`WEAPON_FLARE`)] = 'Flare',

	[tostring(`WEAPON_GRENADELAUNCHER`)] = 'Grenade Launcher',
	[tostring(`WEAPON_RPG`)] = 'RPG',
	[tostring(`WEAPON_MINIGUN`)] = 'Minigun',
	[tostring(`WEAPON_FIREWORK`)] = 'Firework Launcher',
	[tostring(`WEAPON_RAILGUN`)] = 'Railgun',
	[tostring(`WEAPON_HOMINGLAUNCHER`)] = 'Homing Launcher',
	[tostring(`WEAPON_COMPACTLAUNCHER`)] = 'Compact Grenade Launcher',
	[tostring(`WEAPON_RAYMINIGUN`)] = 'Widowmaker',

	[tostring(`WEAPON_PUMPSHOTGUN`)] = 'Pump Shotgun',
	[tostring(`WEAPON_PUMPSHOTGUN_MK2`)] = 'Pump Shotgun Mk2',
	[tostring(`WEAPON_SAWNOFFSHOTGUN`)] = 'Sawed-Off Shotgun',
	[tostring(`WEAPON_BULLPUPSHOTGUN`)] = 'Bullpup Shotgun',
	[tostring(`WEAPON_ASSAULTSHOTGUN`)] = 'Assault Shotgun',
	[tostring(`WEAPON_MUSKET`)] = 'Musket',
	[tostring(`WEAPON_HEAVYSHOTGUN`)] = 'Heavy Shotgun',
	[tostring(`WEAPON_DBSHOTGUN`)] = 'Double Barrel Shotgun',
	[tostring(`WEAPON_AUTOSHOTGUN`)] = 'Sweeper Shotgun',

	[tostring(`WEAPON_REMOTESNIPER`)] = 'Remote Sniper',
	[tostring(`WEAPON_GRENADELAUNCHER_SMOKE`)] = 'Smoke Grenade Launcher',
	[tostring(`WEAPON_PASSENGER_ROCKET`)] = 'Passenger Rocket',
	[tostring(`WEAPON_AIRSTRIKE_ROCKET`)] = 'Airstrike Rocket',
	[tostring(`VEHICLE_WEAPON_SPACE_ROCKET`)] = 'Orbital Cannon',
	[tostring(`VEHICLE_WEAPON_PLANE_ROCKET`)] = 'Plane Rocket',
	[tostring(`WEAPON_STINGER`)] = 'Stinger [Vehicle]',
	[tostring(`VEHICLE_WEAPON_TANK`)] = 'Tank Cannon',
	[tostring(`VEHICLE_WEAPON_SPACE_ROCKET`)] = 'Rockets',
	[tostring(`VEHICLE_WEAPON_PLAYER_LASER`)] = 'Laser',
	[tostring(`VEHICLE_WEAPON_PLAYER_LAZER`)] = 'Lazer',
	[tostring(`VEHICLE_WEAPON_PLAYER_BUZZARD`)] = 'Buzzard',
	[tostring(`VEHICLE_WEAPON_PLAYER_HUNTER`)] = 'Hunter',
	[tostring(`VEHICLE_WEAPON_WATER_CANNON`)] = 'Water Cannon',

	[tostring(`AMMO_RPG`)] = 'Rocket',
	[tostring(`AMMO_TANK`)] = 'Tank',
	[tostring(`AMMO_SPACE_ROCKET`)] = 'Rocket',
	[tostring(`AMMO_PLAYER_LASER`)] = 'Laser',
	[tostring(`AMMO_ENEMY_LASER`)] = 'Laser',
	[tostring(`WEAPON_RAMMED_BY_CAR`)] = 'Rammed by Car',
	[tostring(`WEAPON_FIRE`)] = 'Fire',
	[tostring(`WEAPON_HELI_CRASH`)] = 'Heli Crash',
	[tostring(`WEAPON_RUN_OVER_BY_CAR`)] = 'Run over by Car',
	[tostring(`WEAPON_HIT_BY_WATER_CANNON`)] = 'Hit by Water Cannon',
	[tostring(`WEAPON_EXHAUSTION`)] = 'Exhaustion',
	[tostring(`WEAPON_EXPLOSION`)] = 'Explosion',
	[tostring(`WEAPON_ELECTRIC_FENCE`)] = 'Electric Fence',
	[tostring(`WEAPON_BLEEDING`)] = 'Bleeding',
	[tostring(`WEAPON_DROWNING_IN_VEHICLE`)] = 'Drowning in Vehicle',
	[tostring(`WEAPON_DROWNING`)] = 'Drowning',
	[tostring(`WEAPON_BARBED_WIRE`)] = 'Barbed Wire',
	[tostring(`WEAPON_VEHICLE_ROCKET`)] = 'Vehicle Rocket',
	[tostring(`VEHICLE_WEAPON_ROTORS`)] = 'Rotors',
	[tostring(`WEAPON_AIR_DEFENCE_GUN`)] = 'Air Defence Gun',
	[tostring(`WEAPON_ANIMAL`)] = 'Animal',
	[tostring(`WEAPON_COUGAR`)] = 'Cougar',

	[tostring(`VEHICLE_WEAPON_RCTANK_GUN`)] = 'Invade & Persuade Tank',
	[tostring(`VEHICLE_WEAPON_RCTANK_FLAME`)] = 'Invade & Persuade Tank',
	[tostring(`VEHICLE_WEAPON_RCTANK_ROCKET`)] = 'Invade & Persuade Tank',
	[tostring(`VEHICLE_WEAPON_RCTANK_LAZER`)] = 'Invade & Persuade Tank',
}

ClientTables.deatCause = {
	[`WEAPON_UNARMED`] = {'Beaten', 'Unarmed'},
	[`WEAPON_CROWBAR`] = {'Beaten', 'Crowbar'},
	[`WEAPON_BAT`] = {'Beaten', 'Bat'},
	[`WEAPON_GOLFCLUB`] = {'Beaten', 'Golfclub'},
	[`WEAPON_HAMMER`] = {'Beaten', 'Hammer'},
	[`WEAPON_NIGHTSTICK`] = {'Beaten', 'Nightstick'},

	[`WEAPON_MOLOTOV`] = {'Torched', 'Molotov'},
	[`WEAPON_FLAREGUN`] = {'Torched', 'Flaregun'},

	[`WEAPON_DAGGER`] = {'Stabbed', 'Dagger'},
	[`WEAPON_KNIFE`] = {'Stabbed', 'Knife'},
	[`WEAPON_SWITCHBLADE`] = {'Stabbed', 'Switchblade'},
	[`WEAPON_HATCHET`] = {'Stabbed', 'Hatchet'},
	[`WEAPON_BOTTLE`] = {'Stabbed', 'Bottle'},

	[`WEAPON_SNSPISTOL`] = {'Pistolled', 'SNS Pistol'},
	[`WEAPON_HEAVYPISTOL`] = {'Pistolled', 'Heavy Pistol'},
	[`WEAPON_VINTAGEPISTOL`] = {'Pistolled', 'Vintage Pistol'},
	[`WEAPON_PISTOL`] = {'Pistolled', 'Pistol'},
	[`WEAPON_APPISTOL`] = {'Pistolled', 'AP Pistol'},
	[`WEAPON_COMBATPISTOL`] = {'Pistolled', 'Combat Pistol'},

	[`WEAPON_MICROSMG`] = {'Riddled', 'Micro SMG'},
	[`WEAPON_SMG`] = {'Riddled', 'SMG'},

	[`WEAPON_CARBINERIFLE`] = {'Rifled', 'Carbine Rifle'},
	[`WEAPON_MUSKET`] = {'Rifled', 'Musket'},
	[`WEAPON_ADVANCEDRIFLE`] = {'Rifled', 'Advanced Rifle'},
	[`WEAPON_ASSAULTRIFLE`] = {'Rifled', 'Assult Rifle'},
	[`WEAPON_SPECIALCARBINE`] = {'Rifled', 'Special Carbine'},
	[`WEAPON_COMPACTRIFLE`] = {'Rifled', 'Compact Rifle'},
	[`WEAPON_BULLPUPRIFLE`] = {'Rifled', 'Bullpup Rifle'},

	[`WEAPON_MG`] = {'Machine Gunned', 'MG'},
	[`WEAPON_COMBATMG`] = {'Machine Gunned', 'Combat MG'},

	[`WEAPON_BULLPUPSHOTGUN`] = {'Pulverized', 'Bullpup Shotgun'},
	[`WEAPON_ASSAULTSHOTGUN`] = {'Pulverized', 'Assult Shotgun'},
	[`WEAPON_DBSHOTGUN`] = {'Pulverized', 'Double Barrel Shotgun'},
	[`WEAPON_PUMPSHOTGUN`] = {'Pulverized', 'Pump Shotgun'},
	[`WEAPON_HEAVYSHOTGUN`] = {'Pulverized', 'Heavy Shotgun'},
	[`WEAPON_SAWNOFFSHOTGUN`] = {'Pulverized', 'Sawed-Off Shotgun'},

	[`WEAPON_MARKSMANRIFLE`] = {'Sniped', 'Marksman Rifle'},
	[`WEAPON_SNIPERRIFLE`] = {'Sniped', 'Sniper Rifle'},
	[`WEAPON_HEAVYSNIPER`] = {'Sniped', 'Heavy Sniper'},
	[`WEAPON_ASSAULTSNIPER`] = {'Sniped', 'Assult Sniper'},
	[`WEAPON_REMOTESNIPER`] = {'Sniped', 'Remote Sniper'},

	[`WEAPON_GRENADELAUNCHER`] = {'Obliterated', 'Grenade Launcher'},
	[`WEAPON_RPG`] = {'Obliterated', 'RPG'},
	[`WEAPON_HOMINGLAUNCHER`] = {'Obliterated', 'Homing Launcher'},
	[`WEAPON_FIREWORK`] = {'Obliterated', 'Firework Launcher'},
	[`VEHICLE_WEAPON_TANK`] = {'Obliterated', 'Tank Shell'},

	[`WEAPON_MINIGUN`] = {'Shredded', 'Minigun'},

	[`WEAPON_GRENADE`] = {'Bombed', 'Grenade'},
	[`WEAPON_PROXMINE`] = {'Bombed', 'Proximity Mine'},
	[`WEAPON_EXPLOSION`] = {'Bombed', 'Explosion'},
	[`WEAPON_STICKYBOMB`] = {'Bombed', 'Sticky Bomb'},
	[`WEAPON_PIPEBOMB`] = {'Bombed', 'Pipe Bomb'},

	[`VEHICLE_WEAPON_ROTORS`] = {'Mowed Over', 'Helicopter Rotors'},

	[`WEAPON_RUN_OVER_BY_CAR`] = {'Flattened', 'Vehicle'},
	[`WEAPON_RAMMED_BY_CAR`] = {'Flattened', 'Vehicle'},

	[-842959696] = {'Fell from a high place', nil}
}